AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  OurSqsTopic:
    Type: AWS::SQS::Queue

  TransformFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../example-project/target/sf-1.0-SNAPSHOT.jar # <== use this with 'cloudformation package', else replace with your own S3 path
      Handler: be.branch.sf.ExampleHandler
      Runtime: java17
      MemorySize: 2048
      Timeout: 30
      Policies:
        - AWSLambdaExecute

# TODO add the second function, which will come after the Wait and sends a message to SQS
#  SqsFunction:
#    Type: AWS::Serverless::Function

  MySampleStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Role: !GetAtt SFRole.Arn
      Definition:
        StartAt: Uppercase # <== so our first Task should be named 'Uppercase'
        States:
          # add an 'Uppercase' Task, a Choice and a Wait
          # the 'Greeting' Task (which will write to SQS after the Wait) is already present
          # as is a Fail, the default for Choice
          GreetBoss:
            Type: Task
            Resource: !GetAtt SqsFunction.Arn
            End: true
          Fail:
            Type: Fail

  # Role that allows the step function to invoke Lambdas
  SFRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com # <== note the service
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: "LambdaInvokePol"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'lambda:InvokeFunction'
                Resource: '*'
