AWSTemplateFormatVersion: "2010-09-09"
# look ma, not transforms!

Resources:
  AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # block normal public access
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AssetsBucket
      PolicyDocument:
        # only allow cloudfront's access origin control to get objects
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub ${AssetsBucket.Arn}/*
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${AssetsDistribution}
          - Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub ${AssetsBucket.Arn}/*
              - !GetAtt AssetsBucket.Arn
            Condition:
              Bool:
                aws:SecureTransport: false

  # used to be origin access identity
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Ref AWS::StackName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # used to be 'forwarded values'
  DefaultCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 1
        MaxTTL: 60
        MinTTL: 1
        Name: !Sub '${AWS::StackName}DefaultCachePolicy'
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: false
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              # some example headers
              - Accept
              - Origin
              - Authorization
          QueryStringsConfig:
            QueryStringBehavior: none

# Create a CloudFront distribution that
# - is enabled...
# - has an S3 Origin with an origin access control
# - right domain name *might* be tricky
# - default root index.html
# - default cache for our S3 origin. Should refer to our default cache policy and redirect to https

#  AssetsDistribution:
#    Type: AWS::CloudFront::Distribution
# ...

# you can activate this when the distro has been written
#Outputs:
#  URL:
#    Value: !Sub "https://${AssetsDistribution.DomainName}"
