AWSTemplateFormatVersion: "2010-09-09"
Description: ECR Repository for our Docker Images

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository

Outputs:
  # we are going to need this as input for the next stack
  # and for pushing a docker image
  RepoUri:
    Value: !GetAtt ECRRepository.RepositoryUri
    Description: Uri of our repository
