AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  BranchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://???.jar
      Handler: ???
      Runtime: java17
      MemorySize: 2048
      Timeout: 30
      Policies:
        - AWSLambdaExecute
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ???
            RestApiId: !Ref ApiGatewayApi

  # our api gateway (referenced in the events section)
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

Outputs:
  RestUrl:
    Value: !GetAtt ApiGatewayApi.RestApiId
